#!/usr/bin/env bash

case $HOSTNAME in
    diablo)
	echo ^/etc/bluetooth/main\\.conf$
        echo ^/etc/conf\\.d/apache2$
        echo ^/etc/conf\\.d/display-manager$
        echo ^/etc/cron\\.daily/backup$
        echo ^/etc/cron\\.hourly/backup$
        echo ^/etc/cron\\.monthly/report$
        echo ^/etc/pam\\.d/system-auth$
        echo ^/etc/security/pam_usb\\.conf$
        echo ^/etc/smartd\\.conf$
        echo ^/etc/sysctl\\.conf$
	;;
    
    baal)
	echo ^/etc/dnsmasq\\.conf$
	#echo ^/etc/conf\\.d/hostapd$
	echo ^/etc/cron\\.monthly/report$
	echo ^/etc/dnsmasq\\.conf$
	echo ^/etc/hostapd/hostapd\\.conf$
	#echo ^/etc/hosts$ FIXME needed to find baal?
	echo ^/etc/inittab$
	echo ^/etc/resolv\\.conf\\.head$
	echo ^/etc/smartd\\.conf$
	echo ^/etc/sysctl\\.conf$
	;;

    *)
	;;
esac
