#!/usr/bin/env bash

# cruft/pylon repo
echo ^/usr/bin/\\.git$
cd /usr/bin && git ls-files | sed 's/\(.*\)/\/usr\/bin\/\1/' | sed 's/[^\/]*\(\/.*\)/\1/' | sed 's/\(\/.*\)/\1/' | sed 's/\+/\\+/g' | sed 's/\./\\./g' | sed 's/\(.*\)/^\1$/'

echo ^/usr/bin/games\\.py$

# FIXME gentoo repo for github
echo ^/var/db/repos/fork$

# FIXME search for matching pyc & py in ALL folders, not just PYTHONPATH
# this also results in huge exclusion list from sanity check -> verify this
echo .*\\.pyc$
echo .*\\.pyo$
# add __pycache__ pattern to ignore python3 bytecode dirs (python 3.8 allows to redirect these files with PYTHONPYCACHEPREFIX)
echo .*/__pycache__$

# brother printer driver
echo ^/usr/local/Brother/filter/$
echo ^/usr/libexec/cups/filter/brlpdwrapperMFC7820N$
echo ^/usr/share/cups/model/MFC7820N\\.ppd$

# FIXME assign to some package, this is not covered by FHS 2.3
# Virtual filesystem documenting kernel and process status as text files, e.g., uptime, network.
echo ^/proc$
# Kernel sysfs mount point
echo ^/sys$

# Web applications and data
# As per GLEP 11: http://www.gentoo.org/proj/en/glep/glep-0011.html
# Would like to make this more accurate.
# Hopefully Gentoo will change to /srv/www someday to comply with FHS 2.3.
echo ^/var/www$
