#!/usr/bin/env python

# ignore .pyc & .pyo files for existing .py files in all known python modules
#import os
#import re
#import sys
#python_binaries_re = re.compile(r'.*\.pyc$|.*\.pyo$')
#for path in sys.path:
#    if os.path.exists(path):
#        for root, dirs, files in os.walk(path):
#            for f in files:
#                path = os.path.join(root, f)
#                if python_binaries_re.match(f):
#                    # omit 'c' or 'o' character
#                    if os.path.exists(path[:-1]):
#                        regex = path
#                        regex = regex.replace('+', '\+')
#                        regex = regex.replace('.', '\.')
#                        print('^' + regex + '$')

# eselect python stuff
print('^/usr/bin/idle$')
