#!/bin/bash

# mysql system tables (installed by /usr/bin/mysql_install_db)
echo ^/var/lib/mysql/mysql$

# exclude mysql binary logs if enabled
cat /etc/mysql/my.cnf | grep '^[^#]*log-bin' > /dev/null
if [[ "$?" == 0 ]]; then
    echo ^/var/lib/mysql/mysqld-bin\.
fi

# log files
echo ^/var/log/mysql$
