#!/usr/bin/env bash

# binutils
echo ^/etc/env\\.d/05binutils$
echo ^/etc/env\\.d/binutils/config-`gcc -dumpmachine`$
machine=`gcc -dumpmachine`
ls -1  /usr/$machine/binutils-bin/*/*         | sed "s/.*\/\(.*\)/^\/usr\/bin\/\1$/"  | sed 's/+/\\+/g'
ls -1  /usr/$machine/binutils-bin/*/*         | sed "s/.*\/\(.*\)/^\/usr\/bin\/$machine-\1$/"  | sed 's/+/\\+/g'
ls -1  /usr/$machine/binutils-bin/*/*         | sed "s/.*\/\(.*\)/^\/usr\/$machine\/bin\/\1$/"  | sed 's/+/\\+/g'
echo ^/usr/$machine/lib/ldscripts$

# editor
echo ^/etc/env\\.d/99editor$

# kernel
echo ^/usr/src/linux$

# locale
echo ^/etc/env\\.d/02locale$

# news
cd /var/db/repos
for repo in *; do
    echo ^/var/lib/gentoo/news/news-$repo\\.read$
    echo ^/var/lib/gentoo/news/news-$repo\\.skip$
    echo ^/var/lib/gentoo/news/news-$repo\\.unread$
done

# pager
echo ^/etc/env\\.d/99pager$

# profile
echo ^/etc/portage/make\\.profile$
