#!/usr/bin/env python

import os

logrotate_conf = '/etc/logrotate.conf'
logrotate_dir = '/etc/logrotate.d'

def parse_for_logs(f):
    for l in open(f):
        if l.find('{') != -1:
            for logf in l.rstrip('{').split():
                if os.path.exists(logf):
                    print('^' + logf.replace('.', '\.') + '-[0-9]*\.gz$')

parse_for_logs(logrotate_conf)
for root, dirs, files in os.walk(logrotate_dir):
    for f in files:
        parse_for_logs(os.path.join(root, f))

print('^/var/lib/logrotate\.status$')
