#!/usr/bin/env bash

# ignore objects depending on kernel release
kernel_r=`uname -r`
echo ^/boot/config\(-$kernel_r\)\?\(\\.old\)?$
echo ^/boot/vmlinuz\(-$kernel_r\)\?\(\\.old\)?$
echo ^/boot/System.map\(-$kernel_r\)\?\(\\.old\)?$
echo ^/lib[^/]*/modules/$kernel_r$
echo ^/usr/src/linux-$kernel_r$
