#!/bin/bash

# ignore objects depending on kernel release
kernel_r=`uname -r`
echo ^/boot/config{,\.old,-$kernel_r}$
echo ^/boot/vmlinuz{,\.old,-$kernel_r}$
echo ^/boot/System.map{,\.old,-$kernel_r}$
echo ^/lib[^/]*/modules/$kernel_r$
echo ^/usr/src/linux-$kernel_r$
